#'''Parameters'''#


# --- general --- #

minqual:    30


# --- filter_low_qual --- #

dedup:      False


# --- filter_adapters --- #

trim_exec: '/home/lam4003/bin/Trimmomatic-0.39/trimmomatic-0.39.jar'
trim_adapters: '/home/lam4003/bin/Trimmomatic-0.39/adapters/TruSeq3-PE-2.fa'


# --- filter_host_reads --- #

use_host_filter:         True
host_reference_database: '/workdir/lam4003/Databases/GRCh38_28122022/GCA_000001405.15_GRCh38_genomic'
