#'''Parameters config.'''#


ext: '/home/lam4003/bin/camp_mag-qc/workflow/ext'


# --- cmseq --- #

minqual:    30
mincov:     10
dominant_frq_thrsh:     0.8


# --- quast --- #

min_contig_len:   100
